### ISSUE TITLE
Haciendo sincrono un bucle repl con tareas asíncronas

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-TFG/TFM-SyTWA#3]
No he logrado que el método `promptCLLoop` funcione sincronamente, pero si que funciona mas o menos este código en que el bucle se sustituye por una llamada recursiva desde la callback cada vez que la tarea del comando esta hecha:

```javascript
var readlineSync = require('readline-sync');
var fs = require('fs');
var result10 = null;

var  repl = function() {
  let m;

    let command = readlineSync.question('> ');
    if (m = command.match(/read\s+(\S+)/)) {
	let path = m[1];
	fs.readFile(path, 'utf8', function(err, data) {
		// here we wait for random time
		setTimeout(function() {
	           result10 = data;
                   console.log("async result = "+result10);
		   repl();
		}, Math.floor(Math.random() * 10));
	});
     } else if (command.match(/result/i)) {
        console.log(result10);
        repl();
   } else if (command.match(/bye/i)) {
        console.log(result10);
    }
};

repl();
console.log('Miracle, Outside!!');
```

sigue un ejemplo de ejecución:
```
[~/local/src/javascript/async-examples/part1(master)]$ node loop.js 
> read first-file
Miracle, Outside!!
async result = 10

> result
10

> read second-file
async result = 7

> result
7

>
```

tienes el código [aquí](https://github.com/ULL-ESIT-DSI-1617/async-examples/tree/master/part1) en el fichero loop.js

**Comment by jjlabrador** [comment]
Muchas gracias!

Ayer mismo, conseguí hacer funcionar el bucle usando la interfaz Readline de Node. A priori, no me falla. El código lo puedes encontrar en la rama 'test' (commit ddac2a2)

**Comment by crguezl** [comment]
Que bueno. Buenas noticias!

2017-05-31 20:40 GMT+01:00 Juan José Labrador González <
notifications@github.com>:
